image: node

before_script:
    - npm install

cache:
    paths:
        - node_modules/

build-job:
    stage: build
    script:
        - nuxt build

deploy-prod:
    stage: deploy
    script:
        - npm run generate